title: Tyler James Burch
locale: en_US
url: https://tylerjamesburch.com
repository: tjburch/tjburch.github.io
email:
description: "Senior Data Analyst for the Boston Red Sox. Baseball analytics, data science, and particle physics research."
twitter_username: tylerjburch
github_username: tjburch
minimal_mistakes_skin: dark
search: true

teaser: /images/bosox.png
og_image: /images/bosox.png


plugins: [jekyll-include-cache, jekyll-sitemap, jekyll-assets, jekyll-seo-tag, jekyll-feed]
remote_theme: mmistakes/minimal-mistakes@4.24.0
markdown: kramdown
highlighter: rouge

permalink: /blog/:categories/:title


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WQ3JL3NLY9"
    anonymize_ip: false # default


# Site owner
author:
  name: Tyler James Burch
  avatar: images/bosox.png
  bio: "Applying research methods, statistics, machine learning, and Bayesian modeling to solve problems in professional baseball analytics."
  location: Peabody, MA
  twitter: tylerjburch
  github: tjburch
  linkedin: tylerjburch
  email: burcht11@gmail.com

footer:
  links:
    - label: "Twitter"
      url: "https://twitter.com/tylerjburch"
    - label: "GitHub"
      url: "https://github.com/tjburch"
    - label: "BlueSky"
      url: "https://bsky.app/profile/tylerjamesburch.com"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/tylerjburch/"

after_footer_scripts:
  - /assets/js/nostalgia-mode.js

  